[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

[[headers]]
for = "/*"
[headers.values]
    Access-Control-Allow-Origin = "https://papaya-bellflower-58z8.squarespace.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Max-Age = "86400"
    Cache-Control = "public, max-age=31560000, immutable"
